CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(30) NOT NULL CHECK (role IN ('ADMIN', 'OWNER', 'CUSTOMER', 'PARTNER'))
);
CREATE TABLE cities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE restaurants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id BIGINT NOT NULL REFERENCES cities(id),
    owner_id BIGINT NOT NULL REFERENCES app_users(id),
    name VARCHAR(150) NOT NULL,
    address VARCHAR(500) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE INDEX ix_restaurants_city ON restaurants(city_id, active);
CREATE TABLE menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL REFERENCES restaurants(id),
    name VARCHAR(150) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    price DECIMAL(12,2) NOT NULL CHECK (price > 0),
    stock BIGINT NOT NULL CHECK (stock >= 0),
    available BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE INDEX ix_menu_restaurant ON menu_items(restaurant_id);
CREATE TABLE delivery_partners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES app_users(id),
    city_id BIGINT NOT NULL REFERENCES cities(id),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    active_order_id BIGINT UNIQUE
);
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES app_users(id),
    restaurant_id BIGINT NOT NULL REFERENCES restaurants(id),
    partner_id BIGINT REFERENCES delivery_partners(id),
    status VARCHAR(30) NOT NULL CHECK (status IN ('PLACED','ACCEPTED','PREPARING','OUT_FOR_DELIVERY','DELIVERED','REJECTED','CANCELLED')),
    delivery_address VARCHAR(500) NOT NULL,
    total DECIMAL(14,2) NOT NULL CHECK (total > 0),
    idempotency_key VARCHAR(80) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (customer_id, idempotency_key)
);
ALTER TABLE delivery_partners ADD CONSTRAINT fk_active_order FOREIGN KEY (active_order_id) REFERENCES orders(id);
CREATE INDEX ix_orders_customer ON orders(customer_id, id);
CREATE INDEX ix_orders_restaurant_status ON orders(restaurant_id, status, id);
CREATE INDEX ix_orders_partner ON orders(partner_id, id);
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id),
    menu_item_id BIGINT NOT NULL REFERENCES menu_items(id),
    name VARCHAR(150) NOT NULL,
    unit_price DECIMAL(12,2) NOT NULL CHECK (unit_price > 0),
    quantity INTEGER NOT NULL CHECK (quantity BETWEEN 1 AND 100),
    UNIQUE(order_id, menu_item_id)
);
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE REFERENCES orders(id),
    amount DECIMAL(14,2) NOT NULL CHECK (amount > 0),
    status VARCHAR(20) NOT NULL CHECK (status IN ('CAPTURED', 'REFUNDED')),
    reference VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE order_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id),
    type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    actor_id BIGINT NOT NULL REFERENCES app_users(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX ix_events_order ON order_events(order_id, id);
CREATE TABLE notification_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES order_events(id),
    recipient_id BIGINT NOT NULL REFERENCES app_users(id),
    processed BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE(event_id, recipient_id)
);
CREATE INDEX ix_outbox_pending ON notification_outbox(processed, id);
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outbox_id BIGINT NOT NULL UNIQUE REFERENCES notification_outbox(id),
    recipient_id BIGINT NOT NULL REFERENCES app_users(id),
    order_id BIGINT NOT NULL REFERENCES orders(id),
    event_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX ix_notifications_recipient ON notifications(recipient_id, id);
CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE REFERENCES orders(id),
    restaurant_id BIGINT NOT NULL REFERENCES restaurants(id),
    customer_id BIGINT NOT NULL REFERENCES app_users(id),
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX ix_reviews_restaurant ON reviews(restaurant_id, id);
